providers/gce: fix panic fetching metadata
http::header::HeaderName::from_static() does not accept uppercase
letters.  Introduced in b1e2a5ddbef0.

Fixes panic:
    thread 'main' panicked at 'invalid header name', [...]/http-0.1.14/src/header/name.rs:1660:23