cargo: bump MSRV to 1.88.0 for libflate 2.3
SOLVES:

Caused by:
  feature  is required

  The package requires the Cargo feature called , but that feature is not stabilized in this version of Cargo (1.84.1 (66221abde 2024-11-19)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html\#edition-2024 for more information about the status of this feature.

SOLVES:
   --> /github/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libflate-2.3.0/src/finish.rs:128:12
    |
128 |         if let Some(inner) = self.inner.take()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667\> for more information

error[E0658]:  expressions in this position are unstable
   --> /github/home/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libflate-2.3.0/src/finish.rs:129:16
    |
129 |             && let Err(e) = inner.complete()
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667\> for more information