providers/vmware: add missing public functions for non-amd64
VmwareProvider must have a corresponding empty function
`parse_netplan_config()` in unsupported part as well, just like the
amd64 part.
Otherwise build would fail when cross-building afterburn for arm64.

```
error[E0599]: no method named `parse_netplan_config` found for reference
`&VmwareProvider` in the current scope
  --> src/providers/vmware/mod.rs:37:14
   |
37 |         self.parse_netplan_config()
   |              ^^^^^^^^^^^^^^^^^^^^ method not found in
`&VmwareProvider`
```